// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhhlzsjxfycznoydmiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoaGx6c2p4Znljem5veWRtaXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1MjE0NjMsImV4cCI6MjA1NzA5NzQ2M30.c-LXpGvZeLrx0ZkYySKPcOVb2WiFR3TDBmqrPpoIqUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);